# Generated by Django 3.2.4 on 2021-07-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carts',
            options={'verbose_name': 'Carts', 'verbose_name_plural': 'Carts'},
        ),
    ]
