# Generated by Django 3.2.4 on 2021-07-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_variation_managers'),
        ('Cart', '0003_alter_carts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='Store.Variation'),
        ),
    ]
