# Generated by Django 3.2.4 on 2021-07-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_cartitem_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variation',
            new_name='variations',
        ),
    ]
